#############################################################
##
##  PHP view of Jig workspace
##
#############################################################

class: Zig\View\Document\Workspace
title: Catapatate 2 preview

#############################################################
## HEADER

# GMap key is
# cartapatate.net : ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxQA367lAHlkjABbUcAop0DGCpL_0RR1Fbs6U1WlvDJ0jWdsrgcAgGKukA
# catapatate.net : ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxSDsnPkFEP6x-dHoKmFbN1aOTzr0BQOWNYucEIrZDL4llsOWnS81AteRQ
#

packageScripts: false
packageStyles: false

scripts:
  dojo: /x/dojo/dojo.js
  gmaps: http://maps.google.com/maps/api/js?v=3.3&amp;sensor=false
  #gmaps: http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAbLRoNMqR4Pen1V9KJHqHFxQA367lAHlkjABbUcAop0DGCpL_0RR1Fbs6U1WlvDJ0jWdsrgcAgGKukA
  #proj4js: /js/proj4js/lib/proj4js-compressed.js
  #openLayers: /js/openlayers/build/OpenLayers.js
  application: /x/application.js
  # start code added in dev mixin

scriptAffectations:
  window\.workspaceKey: home
  window\.workspaceObjDeps: []
  #window\.workspaceObjDeps: [GBrowserIsCompatible]

css:
  app: /x/catapatate/css/application.css


#############################################################
## BODY

bodyAttributes:
  class: patate tundra


bodyInnerHtml:
  app:
    tag: div
    attributes:
      id: app
    content: ""
  wait:
    tag: div
    attributes:
      id: wait
    content:
      sub:
        tag: div
        content: "Chargement de l'application..."

widgets:
  root:
    _class: jig.layout.RootPane
    state:
      children:
        - mainContainer
      toaster:
        positionDirection: bl-up
        # "br-up", "br-left", "bl-up", "bl-right", "tr-down", "tr-left", "tl-down", "tl-right"
  mainContainer:
    _class: jig.layout.BorderContainer
    state:
      design: sidebar
      children:
        - map
        - sideContainer
      paneSize: 250
  map:
    _class: ploomap.map.Classical
    state:
      layersDefsClass: catapatate.layerDef.Application
      layers:
        - google_hybrid
        - google_normal
        - google_satellite
        - google_physical
        # - google_aerial
        # - google_aerial_hybrid
        # - google_moon_elevation
        # - google_moon_visible
        # - google_mars_elevation
        # - google_mars_visible
        # - google_mars_infrared
        # - google_sky_visible
      center:      # Paris
        geoloc: true
        x: 260535
        y: 6249816
        zoom: 13
      controls:
        #- OpenLayers.Control.KeyboardDefaults
        - { class: OpenLayers.Control.Navigation, options: { zoomWheelEnabled: true } }
        #, mouseWheelOptions: { interval: 100 } } }
        #- OpenLayers.Control.PanZoomBar
        - { class: ploomap.OpenLayers.Control.SexyZoomBar, options: { numZoomLevels: 22 } }
        - { class: ploomap.OpenLayers.Control.ScaleLine, options: { maxWidth: 150, geodesic: true } }
        - ploomap.OpenLayers.Control.TileLoadSpinner
  sideContainer:
    _class: jig.layout.BorderContainer
    state:
      design: headline
      children:
        - layers
        - overviewMap
        #- about
        #- sideContainer2
      paneSize: 200
  sideContainer2:
    _class: jig.layout.BorderContainer
    state:
      design: headline
      children:
        - about
        - overviewMap
      paneSize: 120
  layers:
    _class: ploomap.tool.Layers
    state:
      mapWidget: map
      appearTarget: bottom
  overviewMap:
    _class: ploomap.tool.OverviewMap
    state:
      mapWidget: map
  about:
    _class: catapatate.info.About

settings:
  layerManager:
    layerLibraryClass: catapatate.layerLibrary.Application
  layers:
    - google_hybrid
    - google_normal
    - google_satellite
    - google_physical
    - google_aerial
    - google_aerial_hybrid
    - google_moon
    - google_moon_elevation
    - google_moon_visible
    - google_mars_elevation
    - google_mars_visible
    - google_mars_infrared
    - google_sky
    - ign
    - geol
    - igc_paris
    - igc_paris_vector
    - igc_versailles
    - igc_versailles_vector
    - osm
    - cassini
    - velib
    - communes_fr
    - plans
    - elements
    #- bss
    - acces
    - lieu
    - galerie
    - grandaxe
    - egout
    - galerie_technique
    - delimitation
    - secteur
    - reseau
  mapTools:
    tools:
      - ploomap.tool.Magnifier
      - ploomap.tool.OverviewMap
      - ploomap.tool.Measure
      - ploomap.tool.Export
      - ploomap.tool.StreetView
      - ploomap.tool.Itineraries
      - jig.tool.UserFeedback
      - catapatate.info.About




  elementTypes:
    acces:
      label: Accès
      layerTitle: Accès
      wikiCategory: Accès
      description: "Accès aux cavités souterraines"
      icon: /images/markers/acces.png
      minResolution: 0.07464553542137146
      maxResolution: 4.777314266967774
      geometry: point
      popupHeight: 310
      attributes:
        name:
          label: Nom
          type: name
        emplacement:
          label: Emplacement
          type: string
          default:
        usage:
          label: "Usage"
          type: select
          default: inconnu
          options:
            ps: "Puits de service"
            peau: "Puits à eau"
            pe: "Puits d'extraction"
            comm: "Puits de communication"
            entree: "Entrée"
            artesien: "Puits artésien"
            autre: "Autre"
            inconnu: "Inconnu"
        acces:
          label: "Accès"
          type: select
          default: inconnu
          options:
            rd_soleil: "Plaque ronde, soleil"
            rd_tortue: "Plaque ronde, tortue"
            rd_egouts: "Plaque ronde, type égouts"
            rd_legere: "Plaque ronde, très légère"
            rd_carree: "Plaque ronde IDC"
            rd_autre: "Plaque ronde, autre type"
            rt_ptt: "Plaque rectangulaire, type PTT"
            rt_triangle: "Plaque rectangulaire, ouverture en triangles"
            rt_complexe: "Plaque rectangulaire, mécanisme complexe"
            rt_autre: "Plaque rectangulaire, autre type"
            plaque: "Autre type de plaque"
            porte: "Porte métallique"
            trou: "Trou percé (chatière)"
            plaquesmetal: "Plaques de métal"
            rien: "Trou sans couverture"
            cavage: "Cavage"
            treuil: "Ouverture sur treuil"
            autre: "Autre type d'accès"
            inexistant: Inexistant
            inconnu: "Inconnu"
        acces_detaille:
          label: "Accès détaillé"
          type: select
          default: non_precise
          options:
            non_precise: Non précisé
            carriere_idc: Carrières - IDC
            carriere_soleil: Carrières - soleil
            carriere_idc_soleil: Carrières - IDC+soleil
            carriere_double_battants_triangles: Carrières - double-battants - triangles
            carriere_double_battants_beton: Carrières - double-battants - béton
            carriere_double_battants_metal: Carrières - double-battants - métal
            carriere_mutiples_battants_3: Carrières - multiples-battants - 3
            carriere_mutiples_battants_4: Carrières - multiples-battants - 4
            carriere_mutiples_battants_5: Carrières - multiples-battants - 5
            carriere_mutiples_battants_6+: Carrières - multiples-battants - 6+
            egout_quadrillage_grave: Égout - quadrillage gravé
            egout_sans_marquage: Égout - sans marquage
            egout_vanne: "Égout - avec vanne d'eau"
            egout_patte_doie: "Égout - petite avec motif patte d'oie"
            egout_legere_languette: Égout - légère à languette
            egout_lourde_languette: Égout - lourde à languette
            ratp_grille: RATP - grille
            ratp_claire_voie: RATP - claire voie
            ratp_claire_voie_grille: RATP - claire-voie entourée de grille
            edf: EDF
            edf_cpde: EDF - CPDE
            edf_cpde_mht: EDF - CPDE-MHT
            edf_verrins: EDF - à verrins
            edf_victor_popp: Plaques EDF (Victor Popp)
            ptt_rdlr: PTT - RDLR
            ptt_barat: PTT - BARAT
            ptt_sebel: PTT - SEBEL
            ptt_trefle: PTT - sans marquage, serrure trèfle
            ptt_accroche: "PTT - sans marquage, trou d'accroche"
            ptt_carree_esperluette: 'Plaques PTT carrées (esperluette)'
            ptt_carree_quadrillage: Plaques PTT carrées (quadrillage gravé)
            ptt_double_triangle: Plaques PTT à double triangle
            ptt_double_triangle_multiples: Plaques PTT à double triangle multiple
            tortue_petite: Plaques tortues petites
            tortue_moyenne: Plaques tortues moyennes
            tortue_grande: Plaques tortue grandes
            tampon_pierre: Tampons en pierre
            couvercle_beton: Couvercles en béton
            plaque_acier_uasm: Plaques type acier/UASM
            trappe_inclinee: Trappes inclinées simples
            trappe_inclinee_battants: Trappes inclinées 2+ battants
            porte: Portes
            porte_metal: Portes en métal
            porte_bois: Portes en bois
            porte_grillagee: Portes grillagées
            porte_carossable: Portes carrossables
            porte_et_plaque: Portes avec plaque
            port_grille_multiple: Portes/grilles multiples
            grille_mobile: Grilles mobiles
            grille_fixe: Grilles fixes
            grillage: Grillages
            chatiere_verticale: Chatières verticales simples
            chatiere_horizontale: Chatières horizontales simples
            cavage_pieton: Cavages piéton simples
            cavage_vehicule: Cavages véhicules simples
            fontis: Fontis
        descente:
          label: Descente
          type: select
          default:
          options:
            pt: "Puits"
            pt_ech: "Puits à échelons"
            pt_sech: "Puits sans échelons"
            pt_echll: "Puits à échelle"
            esc: "Escalier en colimaçon"
            esc_dr: "Escalier droit"
            pente_douce: "Pente douce"
            chatiere: "Chatière"
            simple: "Simple"
            aucune: "Aucune"
            autre: "Autre"
            inconnu: "Inconnu"
        etat_general:
          label: État général
          type: select
          default: inconnu
          options:
            inconnu: Inconnu
            condamne: Condamné
            ferme: Fermé
            ouvert: Ouvert
        etat:
          label: État
          type: select
          default: inconnu
          options:
            ouvert: Ouvert
            difficile: Difficile
            soudure: Soudé
            clef: "Fermé à clef"
            beton: Bétonné
            recouvement: Recouvert
            comblement: Comblé
            disparu: Disparu
            goudron: Goudronné
            enseveli: Enseveli
            amarre: Amarré
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:

    lieu:
      label: Lieu
      description: "Lieux particuliers des cavités souterraines"
      layerTitle: Lieux
      wikiCategory: Lieux
      icon: /images/markers/lieu.png
      minResolution: 0.07464553542137146
      maxResolution: 4.777314266967774
      geometry: point
      attributes:
        name:
          label: Nom
          type: name
          default:
        categorie:
          label: Type
          type: select
          options:
            salle: "Salle"
            squat: "Squat"
            reseau: "Réseau"
            chatiere: "Chatière"
            fontis: "Fontis"
            puits_a_eau_carriere: "Puits à eau (en carrière)"
            puits_a_eau_surface: "Puits à eau (en surface)"
            curiosite: "Curiosité"
            abri: "Abri de défense passive"
            lieudit: "Lieu-dit"
            ossuaire: "Ossuaire"
            cabinet: "Cabinet minéralogique"
            champignonniere: "Champignonnière"
            brasserie: "Brasserie"
            cave_carriere: "Cave-carrière"
            batiment_surface: "Bâtiment en surface"
            crypte: "Crypte"
            grotte: Grotte
            autre: "Autre"
        taille:
          label: Taille
          type: string
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    galerie:
      label: Galerie
      layerTitle: Galeries
      wikiCategory: Galeries
      description: "Galeries en carrière"
      icon: /images/icons/layer_element_galerie.png
      minResolution: 0.07464553542137146
      maxResolution: 2.388657133483887
      geometry: lineString
      attributes:
        name:
          label: Nom
          type: name
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    grandaxe:
      label: Grand axe
      layerTitle: Grands axes
      wikiCategory: Grands axes
      description: "Galeries principales en carrière"
      icon: /images/icons/layer_element_grandaxe.png
      minResolution: 0.07464553542137146
      maxResolution: 38.21851413574219
      geometry: lineString
      attributes:
        name:
          label: Nom
          type: name
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    egout:
      label: "Cours d'eau"
      layerTitle: "Cours d'eau"
      wikiCategory: "Cours d'eau"
      description: "Cours d'eau enterrés - naturel ou artificiel"
      icon: /images/icons/layer_element_egout.png
      minResolution: 0.07464553542137146
      maxResolution: 38.21851413574219
      geometry: lineString
      attributes:
        name:
          label: Nom
          type: name
          default:
        usage:
          label: Type
          type: select
          default: inconnu
          options:
            collecteur: "Égout collecteur"
            orage: "Déversoir d'orage"
            simple: "Galerie d'égouts simple"
            acqueduc: Aqueduc
            riviere_souterraines: Rivière souterraine
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:

    galerie_technique:
      label: Galerie technique
      layerTitle: G. techniques
      wikiCategory: Galeries techniques
      description: "Galeries techniques (PTT, électricité...)"
      icon: /images/icons/layer_element_galerie_technique.png
      minResolution: 0.07464553542137146
      maxResolution: 38.21851413574219
      geometry: lineString
      attributes:
        name:
          label: Nom
          type: name
          default:
        usage:
          label: Type
          type: select
          default: inconnu
          options:
            ptt: PTT
            edf: EDF
            ratp: RATP
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:

    delimitation:
      label: Délimitation
      layerTitle: Délimitations
      wikiCategory: Délimitations
      description: "Délimitations diverses"
      icon: /images/icons/layer_element_delimitation.png
      geometry: polygon
      attributes:
        name:
          label: Nom
          type: name
          default:
        objet:
          label: Objet
          type: select
          default: inconnu
          options:
            enceinte: Enceinte
            admini: Délimitation administrative
            geol: Délimitation géologique
            autre: Autre délimitation
        remarques:
          label: Remarques
          type: textarea
          default:

    secteur:
      label: Secteur
      layerTitle: Secteurs
      wikiCategory: Secteurs
      description: "Secteurs de cavités souterraines délimité par un critère quelconque"
      icon: /images/icons/layer_element_secteur.png
      minResolution: 1.1943285667419434
      maxResolution: 38.21851413574219
      geometry: polygon
      attributes:
        name:
          label: Nom
          type: name
          default:
        remarques:
          label: Observations
          type: textarea
          default:

    reseau:
      label: Réseau
      layerTitle: Réseaux
      wikiCategory: Réseaux
      description: "Réseau de galeries communiquantes appartenant à une ou plusieurs exploitations en carrière"
      icon: /images/icons/layer_element_reseau.png
      minResolution: 4.777314266967774
      maxResolution: 76.43702827148438
      geometry: polygon
      attributes:
        name:
          label: Nom
          type: name
          default:
        type:
          label: Type
          type: select
          default: non_precise
          options:
            non_precise: Non précisé
            carriere: Carrière
            mine: Mine
        exploitation:
          label: Exploitation
          type: select
          default: inconnu
          options:
            calcaire: Calcaire
            craie: Craie
            gypse: Gypse
            marne: Marne
            sable: Sable
            argile: Argile
            lignite: Lignite
            houille: Houille
            argent: Argent
            diamant: Diamant
            or: Or
            autre: Autre
            inconnu: Inconnu
        remarques:
          label: Observations
          type: textarea
          default:
