geonef_zig:
  install:
    # all paths are relative to the parameter 'kernel.root_dir'
    #manager_class: hehe
    public_dir: %kernel.cache_dir%/public
    public_mappings:
      - { location: '', directory: '../src/Geonef/CarnetsBundle/Resources/public' }
      - { location: '', directory: '../vendor/cartapatate' }
      - { location: 'js', directory: '../vendor/ploomap-client/src' }
      - { location: 'js', directory: '../vendor/jig/src' }
      - { location: 'images/openlayers', directory: '../vendor/openlayers/img' }
      - { location: 'js/openlayers', directory: '../vendor/openlayers' }
      - { location: 'js/proj4js', directory: '../vendor/proj4js' }
      - { location: 'js/dojo', directory: '../vendor/dojo-release/dojo' }
      - { location: 'js/dijit', directory: '../vendor/dojo-release/dijit' }
      - { location: 'js/dojox', directory: '../vendor/dojo-release/dojox' }

    shrinksafe:
      buildscripts_dir: ../vendor/dojo-release/util/buildscripts
      release_name: x
      release_dir: %kernel.cache_dir%/public
      build_version: 0.2.16
      profileData:
        prefixes:
          - { ns: dojo, path: %kernel.cache_dir%/public/js/dojo }
          - { ns: dijit, path: %kernel.cache_dir%/public/js/dijit }
          - { ns: dojox, path: %kernel.cache_dir%/public/js/dojox }
          - { ns: jig, path: %kernel.cache_dir%/public/js/jig }
          - { ns: ploomap, path: %kernel.cache_dir%/public/js/ploomap }
          - { ns: cartapatate, path: %kernel.cache_dir%/public/js/cartapatate }
          - { ns: catapatate, path: %kernel.cache_dir%/public/js/catapatate }
          - { ns: package, path: %kernel.cache_dir%/public/js/package }
        layers:
          -
            name: ../application.js
            copyrightFile: '../vendor/ploomap-client/src/ploomap/copyright.txt'
            dependencies:
              - cartapatate.start.loadWorkspace
              - package.application
