title: "Catapatate [DEV]"

# uncomment this to get non-schrinked dojo
#scripts.dojo: /js/dojo/dojo.js

css.app: /js/catapatate/css/application.css

scriptAffectations.window\.devMode: true

bodyAttributes.class: patate tundra dev
