imports:
  - { resource: doctrine.yml }
  - { resource: zig.install.yml }
  - { resource: pglink.yml }

app.config:
  name: catapatate
  charset: UTF-8
  error_handler: null
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
  validation: { enabled: true, annotations: true }
  templating: ~
    #escaping: htmlspecialchars
    #renderers:
  #session
  #translator:
  #  fallback:

twig.config: ~

zig.registry: ~

zig.api: ~

swiftmailer.config: ~

