imports:
  - { resource: doctrine.yml }
  - { resource: zig.install.yml }
  - { resource: pglink.yml }

framework:
  #name: catapatate
  charset: UTF-8
  error_handler: null
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
  validation: { enabled: true, annotations: true }
  templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    #escaping: htmlspecialchars
    #renderers:
  #session
  #translator:
  #  fallback:

twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

zig: ~

swiftmailer: ~

