#catapatate:
#  resource: CatapatateBundle/Resources/config/routing.yml
zig:
  resource: "@ZigBundle/Resources/config/routing.yml"
# ploomap:
#   resource: "@Ploomap/Resources/config/routing.yml"

homepage:
  pattern: /
  defaults: { _controller: "ZigBundle:ViewClass:render", path: "views.workspace" }

admin:
  pattern: /admin
  defaults: { _controller: "ZigBundle:ViewClass:render", path: "views.admin" }

