zig:
  install:
    # all paths are relative to the parameter 'kernel.root_dir'
    #manager_class: hehe
    public_dir: public
    public_mappings:
      - { location: '', directory: '../lib/carnets/client' }
      - { location: '', directory: '../lib/cartapatate/client' }
      - { location: '', directory: '../lib/ploomap/client' }
      - { location: '', directory: '../lib/zig/client' }
      - { location: 'images/openlayers', directory: '../lib/openlayers/img' }
      - { location: 'js/openlayers', directory: '../lib/openlayers' }
      - { location: 'js/proj4js', directory: '../lib/proj4js' }
      - { location: 'js/dojo', directory: '../lib/dojo-release/dojo' }
      - { location: 'js/dijit', directory: '../lib/dojo-release/dijit' }
      - { location: 'js/dojox', directory: '../lib/dojo-release/dojox' }

    shrinksafe:
      buildscripts_dir: ../lib/dojo-release/util/buildscripts
      release_name: x
      release_dir: public
      build_version: 0.2.16
      profileData:
        prefixes:
          - { ns: dojo, path: public/js/dojo }
          - { ns: dijit, path: public/js/dijit }
          - { ns: dojox, path: public/js/dojox }
          - { ns: jig, path: public/js/jig }
          - { ns: ploomap, path: public/js/ploomap }
          - { ns: cartapatate, path: public/js/cartapatate }
          - { ns: catapatate, path: public/js/catapatate }
          - { ns: package, path: public/js/package }
        layers:
          -
            name: ../application.js
            copyrightFile: '../lib/ploomap/client/js/ploomap/copyright.txt'
            dependencies:
              - cartapatate.start.loadWorkspace
              - package.application
